name: Pull requests

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test_and_build:
    name: "Unit tests and build APK"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check build-logic
        run: ./gradlew check -p build-logic

      - name: Unit tests
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew app:assembleDebug